name: 'App Deployment Prep'
description: 'Prepare for app deployment'
inputs:
  versionFile:
    description: 'name of the version file'
    required: true
    default: 'version.txt'    
  csproj:
    description: 'Path of the csproj file'
    required: true
    default: './placemyorder/placemyorder.csproj' 
  branch:
    description: 'Branch name'
    required: true
    default: 'master'     
runs:
  using: "composite"
  steps:  
      - name: Autoincrement version
        shell: pwsh
        run: |          
          ./deploy/scripts/autoincrementversion.ps1 -versionFile ${{ inputs.versionFile }} -branch ${{ inputs.branch }}
          Set-Location ${{ github.workspace }}
      - name: Fetch current version
        shell: bash
        run: |
          VER=$(cat ${{ inputs.versionFile }})
          echo "AppVersion=$VER" >> $GITHUB_ENV
      - name: Version the App
        uses: managedcode/MAUIAppVersion@v1     
        with:
          csproj: ${{ inputs.csproj }}
          version: ${{ github.run_number }} # to keep value unique
          displayVersion: ${{ env.AppVersion }}
          printFile: false   
      - name: Install Firebase Cli
        shell: bash
        run: |
          npm install -g firebase-tools            